// pages/[...image].tsx
import Images from "next/image";
import Head from "next/head";
import fetch from "node-fetch";
import { Image, Text, Box, SimpleGrid } from "@chakra-ui/react";
const ImagePage = ({ imageUrl, found, data }: any) => {
	return (
		<Box>
			<Box>
				<Head>
					{found ? (
						""
					) : !data.embed ? (
						<meta property="og:url" content={imageUrl} />
					) : (
						<>
							{data.embed.title ? <title>{data.embed.title}</title> : ""}
							{data.embed.url ? <meta name="og:url" content={data.embed.url} /> : ""}
							{data.embed.description ? <meta name="description" content={data.embed.description} /> : ""}
							{data.embed.color ? <meta property="theme-color" content={data.embed.color} /> : ""}
						</>
					)}

					<meta property="twitter:card" content="summary_large_image" />
					<link rel="icon" href="/favicon.ico" />

					<meta property="og:image" content={imageUrl} />
				</Head>

				{!found ? (
					<Box bgGradient="linear(to-r, green.200, pink.500)" height="100vh" fontWeight="bold">
						<SimpleGrid justifyItems="center">
							<Text fontSize="3xl">Captured by {`${data?.user_name}`}</Text>
						</SimpleGrid>
						<SimpleGrid justifyItems="center">
							<Image maxW="80rem" maxH="80rem" height="auto" width="auto" src={imageUrl} alt="" onClick={() => window.open(imageUrl)} />
						</SimpleGrid>
					</Box>
				) : (
					"IMAGE NOT FOUND"
				)}
			</Box>
		</Box>
	);
};
ImagePage.getInitialProps = async ({ res, req, query: { image } }: any) => {
	const imageUrl = `${process.env.BACKENDURL || "https://api.tricked.pro/images"}/raw/${image[image.length - 1]}`;
	const e = await fetch(`${process.env.BACKENDURL || "https://api.tricked.pro/images"}/stats/${image[image.length - 1]}`);
	let data = await e.json();
	if (data?.redirect) {
		res.writeHead(308, { Location: data.redirect });
		res.end();
		return {
			fount: false,
			redirect: {
				destination: "/",
				permanent: false,
			},
		};
	}
	return { imageUrl: imageUrl, found: e.status == 404, data: data };
};
export default ImagePage;

// src/routes/[...image].svelte
<script context="module" lang="ts">
	import { getImage } from '$lib/api';

	export const ssr = true;
	export const prerender = true;
	export const hydrate = false;
	export const router = false;
	// export const prerender = true;
	/**
	 * @type {import('@sveltejs/kit').Load}
	 */
	export async function load({ page }) {
		const { image } = page.params;
		let params = image?.split('/');

		if (params && params[params?.length - 1].split('.')?.[1]) {
			return {
				status: 404,
				error: new Error('Not found')
			};
		}
		let data = await getImage(params[params?.length - 1]);
		if (data.success === false)
			return {
				status: 404,
				error: new Error('Not found')
			};
		if (data.redirect && data.content_type === 'redirect') {
			return {
				status: 302,
				redirect: data.redirect
			};
		}

		return {
			props: { ...data, url: params[params?.length - 1] }
		};
	}
</script>

<script lang="ts">
	export let user_name;
	export let embed: Record<string, string> = {};
	export let url;
	import '../image.css';
	import '../app.css';
</script>

<svelte:head>
	<title>{user_name} | Image Uploader</title>
	{#if embed.title}
		<meta name="title" content={embed.title} />
		<meta property="og:title" content={embed.title} />
		<meta property="twitter:title" content={embed.title} />
		/>{/if}
	{#if embed.description}
		<meta name="description" content={embed.description} />
		<meta property="og:description" content={embed.description} />
		<meta property="twitter:description" content={embed.description} />
	{/if}

	<meta property="og:type" content="website" />
	<meta property="og:image" content={`https://api.tricked.pro/images/raw/${url}`} />
	<meta property="twitter:card" content="summary_large_image" />
	<meta property="theme-color" content={embed.color} />
</svelte:head>

<div class="main">
	<p class="text text-white">captured by {user_name}</p>
	<img
		style={`border: 9px solid ${embed.color || '#00a41b'}`}
		class="image"
		alt=""
		src={`https://api.tricked.pro/images/raw/${url}`}
	/>
</div>
