// src/routes/[...image].svelte
<script context="module" lang="ts">
	import { getImage } from '$lib/api';

	export const ssr = true;
	export const prerender = true;
	export const hydrate = false;
	export const router = false;
	// export const prerender = true;
	/**
	 * @type {import('@sveltejs/kit').Load}
	 */
	export async function load({ page }) {
		const { image } = page.params;
		let params = image?.split('/');

		if (params && params[params?.length - 1].split('.')?.[1]) {
			return {
				status: 404,
				error: new Error('Not found')
			};
		}
		let data = await getImage(params[params?.length - 1]);
		if (data.success === false)
			return {
				status: 404,
				error: new Error('Not found')
			};
		if (data.redirect && data.content_type === 'redirect') {
			return {
				status: 302,
				redirect: data.redirect
			};
		}

		return {
			props: { ...data, url: params[params?.length - 1] }
		};
	}
</script>

<script lang="ts">
	export let user_name;
	export let embed: Record<string, string> = {};
	export let url;
	import '../image.css';
	import '../app.css';
</script>

<svelte:head>
	<title>{user_name} | Image Uploader</title>
	{#if embed.title}
		<meta name="title" content={embed.title} />
		<meta property="og:title" content={embed.title} />
		<meta property="twitter:title" content={embed.title} />
		/>{/if}
	{#if embed.description}
		<meta name="description" content={embed.description} />
		<meta property="og:description" content={embed.description} />
		<meta property="twitter:description" content={embed.description} />
	{/if}

	<meta property="og:type" content="website" />
	<meta property="og:image" content={`https://api.tricked.pro/images/raw/${url}`} />
	<meta property="twitter:card" content="summary_large_image" />
	<meta property="theme-color" content={embed.color} />
</svelte:head>

<div class="main">
	<p class="text text-white">captured by {user_name}</p>
	<img
		style={`border: 9px solid ${embed.color || '#00a41b'}`}
		class="image"
		alt=""
		src={`https://api.tricked.pro/images/raw/${url}`}
	/>
</div>

// pages/[image].tsx
import Images from "next/image";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import fetch from "node-fetch";
const ImagePage = ({ imageUrl, found, data }: any) => {
	return (
		<div className={styles.coolbackground}>
			<div className={styles.container}>
				<Head>
					{!found ? (
						""
					) : !data.embed ? (
						""
					) : (
						<>
							{data.embed.title ? <title>{data.embed.title}</title> : ""}
							{data.embed.url ? <meta name="og:url" content={data.embed.url} /> : ""}
							{data.embed.description ? <meta name="description" content={data.embed.description} /> : ""}
							{data.embed.color ? <meta property="theme-color" content={data.embed.color} /> : ""}
						</>
					)}
					{/* <title>{`${name || 'Tricked has images'}`}</title> */}
					{/* <meta name="description" content="he uploads them on this website" /> */}
					{/* <meta property="theme-color" content={color} /> */}
					{/* <meta property="og:type" content="website" /> */}
					<meta property="twitter:card" content="summary_large_image" />
					<link rel="icon" href="/favicon.ico" />
					<meta property="og:url" content={imageUrl} />
					<meta property="og:image" content={imageUrl} />
				</Head>
				<style jsx global>{`
					html,
					body {
						// background: radial-gradient(
						// 	ellipse at center,
						// 	#1d3e66 0%,
						// 	#203956 20%,
						// 	#0d1d31 30%,
						// 	#191e3a 50%,
						// 	#10142b 75%,
						// 	#0c0d13 100%
						// );
					}
					main {
						text-align: center;
					}
				`}</style>
				{!found ? (
					<main>
						<h2>
							Captured by {`${data.user.name}`} amount of {`${data.user.name}`} images: {`${data.user.uploads}`}
						</h2>
						<img src={imageUrl} alt="" className={styles.image} onClick={() => window.open(imageUrl)} />
					</main>
				) : (
					"IMAGE NOT FOUND"
				)}

				<footer className={styles.footer}>
					<a href="https://vercel.com" target="_blank" rel="noopener noreferrer">
						Powered by{" "}
						<span className={styles.logo}>
							<Images src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
						</span>
					</a>
				</footer>
			</div>
		</div>
	);
};
ImagePage.getInitialProps = async ({ query: { image } }: { query: any }) => {
	const imageUrl = `${process.env.BACKENDURL || "https://sogga.herokuapp.com"}/view/${image}`;
	const e = await fetch(imageUrl + "/stats");
	return { imageUrl: imageUrl, found: e.status == 404, data: await e.json() };
};
export default ImagePage;
